require: rubocop-rspec

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/BlockLength:
  Max: 100

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*
  TargetRubyVersion: 2.3
