---
development:
  cloud_name: drjyg2me7
  api_key: '492824283696393'
  api_secret: y7ClEx0IJ0IsTd2pSC_n5BhDb2w
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drjyg2me7
  api_key: '492824283696393'
  api_secret: y7ClEx0IJ0IsTd2pSC_n5BhDb2w
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drjyg2me7
  api_key: '492824283696393'
  api_secret: y7ClEx0IJ0IsTd2pSC_n5BhDb2w
  enhance_image_tag: true
  static_image_support: false
